//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;
using CMS.MediaLibrary;

namespace ConvenienceCare
{
	/// <summary>
	/// Represents a page of type <see cref="File"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class File : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "ConvenienceCare.File";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// FileName.
		/// </summary>
		public string FileName { get; set; }


		/// <summary>
		/// Title.
		/// </summary>
		public string Title { get; set; }


		/// <summary>
		/// Date.
		/// </summary>
		public DateTime Date { get; set; }


		/// <summary>
		/// FileDescription.
		/// </summary>
		public string FileDescription { get; set; }


		/// <summary>
		/// RollupImage.
		/// </summary>
		public IEnumerable<AssetRelatedItem> RollupImage { get; set; }


		/// <summary>
		/// FileAttachment.
		/// </summary>
		public IEnumerable<AssetRelatedItem> FileAttachment { get; set; }
	}
}