//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;
using CMS.MediaLibrary;
using ConvenienceCares.org;

namespace Convenience
{
    /// <summary>
    /// Represents a page of type <see cref="Page"/>.
    /// </summary>
    [RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
    public partial class Page : IWebPageFieldsSource, ISocialMetaTags
    {
        /// <summary>
        /// Code name of the content type.
        /// </summary>
        public const string CONTENT_TYPE_NAME = "Convenience.Page";


        /// <summary>
        /// Represents system properties for a web page item.
        /// </summary>
        [SystemField]
        public WebPageFields SystemFields { get; set; }


        /// <summary>
        /// Date.
        /// </summary>
        public DateTime Date { get; set; }


        /// <summary>
        /// Title.
        /// </summary>
        public string Title { get; set; }


        /// <summary>
        /// HeaderImage.
        /// </summary>
        public IEnumerable<AssetRelatedItem> HeaderImage { get; set; }


        /// <summary>
        /// SectionHeader.
        /// </summary>
        public string SectionHeader { get; set; }


        /// <summary>
        /// Description.
        /// </summary>
        public string Description { get; set; }


        /// <summary>
        /// RollupImage.
        /// </summary>
        public IEnumerable<AssetRelatedItem> RollupImage { get; set; }


        /// <summary>
        /// PageContent.
        /// </summary>
        public string PageContent { get; set; }


        /// <summary>
        /// Image.
        /// </summary>
        public IEnumerable<AssetRelatedItem> Image { get; set; }


        /// <summary>
        /// NavType.
        /// </summary>
        public string NavType { get; set; }


        /// <summary>
        /// NavShowChildren.
        /// </summary>
        public bool NavShowChildren { get; set; }


        /// <summary>
        /// LeftNavShowTitle.
        /// </summary>
        public bool LeftNavShowTitle { get; set; }


        /// <summary>
        /// LeftNavTitleOverride.
        /// </summary>
        public string LeftNavTitleOverride { get; set; }


        /// <summary>
        /// SendOwnerReminderEmails.
        /// </summary>
        public string SendOwnerReminderEmails { get; set; }


        /// <summary>
        /// ReminderEmailInterval.
        /// </summary>
        public string ReminderEmailInterval { get; set; }


        /// <summary>
        /// SocialMediaHandler.
        /// </summary>
        public string SocialMediaHandler { get; set; }


        /// <summary>
        /// DefaultTitle.
        /// </summary>
        public string DefaultTitle { get; set; }


        /// <summary>
        /// DefaultDescription.
        /// </summary>
        public string DefaultDescription { get; set; }


        /// <summary>
        /// DefaultImage.
        /// </summary>
        public string DefaultImage { get; set; }
    }
}