//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace NACSShow
{
	/// <summary>
	/// Represents a content item of type <see cref="Speaker"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Speaker : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "NACSShow.Speaker";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// Title.
		/// </summary>
		public string Title { get; set; }


		/// <summary>
		/// Track.
		/// </summary>
		public IEnumerable<TagReference> Track { get; set; }


		/// <summary>
		/// Image.
		/// </summary>
		public ContentItemAsset Image { get; set; }


		/// <summary>
		/// HeaderImageMobile.
		/// </summary>
		public ContentItemAsset HeaderImageMobile { get; set; }


		/// <summary>
		/// ImageAltText.
		/// </summary>
		public string ImageAltText { get; set; }


		/// <summary>
		/// SubHead.
		/// </summary>
		public string SubHead { get; set; }


		/// <summary>
		/// SectionHeader.
		/// </summary>
		public string SectionHeader { get; set; }


		/// <summary>
		/// PageContent.
		/// </summary>
		public string PageContent { get; set; }


		/// <summary>
		/// Company.
		/// </summary>
		public string Company { get; set; }


		/// <summary>
		/// JobTitle.
		/// </summary>
		public string JobTitle { get; set; }


		/// <summary>
		/// FirstName.
		/// </summary>
		public string FirstName { get; set; }


		/// <summary>
		/// LastName.
		/// </summary>
		public string LastName { get; set; }


		/// <summary>
		/// HeaderImage.
		/// </summary>
		public ContentItemAsset HeaderImage { get; set; }


		/// <summary>
		/// NavShowChildren.
		/// </summary>
		public bool NavShowChildren { get; set; }


		/// <summary>
		/// LeftNavShowTitle.
		/// </summary>
		public bool LeftNavShowTitle { get; set; }


		/// <summary>
		/// LeftNavTitleOverride.
		/// </summary>
		public string LeftNavTitleOverride { get; set; }


		/// <summary>
		/// SendOwnerReminderEmails.
		/// </summary>
		public bool SendOwnerReminderEmails { get; set; }


		/// <summary>
		/// ReminderEmailInterval.
		/// </summary>
		public string ReminderEmailInterval { get; set; }


		/// <summary>
		/// Description.
		/// </summary>
		public string Description { get; set; }


		/// <summary>
		/// RollupImage.
		/// </summary>
		public ContentItemAsset RollupImage { get; set; }


		/// <summary>
		/// NavType.
		/// </summary>
		public string NavType { get; set; }


		/// <summary>
		/// SpeakerGUID.
		/// </summary>
		public Guid SpeakerGUID { get; set; }


		/// <summary>
		/// WebsiteURL.
		/// </summary>
		public string WebsiteURL { get; set; }
	}
}