//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;
using CMS.MediaLibrary;

namespace NACSShow
{
	/// <summary>
	/// Represents a page of type <see cref="Workshop"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Workshop : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "NACSShow.Workshop";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// Title.
		/// </summary>
		public string Title { get; set; }


		/// <summary>
		/// Day.
		/// </summary>
		public string Day { get; set; }


		/// <summary>
		/// Icon.
		/// </summary>
		public string Icon { get; set; }


		/// <summary>
		/// HeaderImageMobile.
		/// </summary>
		public IEnumerable<AssetRelatedItem> HeaderImageMobile { get; set; }


		/// <summary>
		/// SubHead.
		/// </summary>
		public string SubHead { get; set; }


		/// <summary>
		/// Capacity.
		/// </summary>
		public int Capacity { get; set; }


		/// <summary>
		/// StartTime.
		/// </summary>
		public DateTime StartTime { get; set; }


		/// <summary>
		/// EndTime.
		/// </summary>
		public DateTime EndTime { get; set; }


		/// <summary>
		/// HeaderImage.
		/// </summary>
		public IEnumerable<AssetRelatedItem> HeaderImage { get; set; }


		/// <summary>
		/// Description.
		/// </summary>
		public string Description { get; set; }


		/// <summary>
		/// SectionHeader.
		/// </summary>
		public string SectionHeader { get; set; }


		/// <summary>
		/// RollupImage.
		/// </summary>
		public IEnumerable<AssetRelatedItem> RollupImage { get; set; }


		/// <summary>
		/// PageContent.
		/// </summary>
		public string PageContent { get; set; }


		/// <summary>
		/// Image.
		/// </summary>
		public IEnumerable<AssetRelatedItem> Image { get; set; }


		/// <summary>
		/// LeftNavShowTitle.
		/// </summary>
		public bool LeftNavShowTitle { get; set; }


		/// <summary>
		/// SendOwnerReminderEmails.
		/// </summary>
		public string SendOwnerReminderEmails { get; set; }


		/// <summary>
		/// ReminderEmailInterval.
		/// </summary>
		public string ReminderEmailInterval { get; set; }


		/// <summary>
		/// LeftNavTitleOverride.
		/// </summary>
		public string LeftNavTitleOverride { get; set; }


		/// <summary>
		/// ImageAltText.
		/// </summary>
		public string ImageAltText { get; set; }


		/// <summary>
		/// NavType.
		/// </summary>
		public string NavType { get; set; }


		/// <summary>
		/// ShowID.
		/// </summary>
		public int ShowID { get; set; }


		/// <summary>
		/// NavShowChildren.
		/// </summary>
		public bool NavShowChildren { get; set; }


		/// <summary>
		/// TimeSlot.
		/// </summary>
		public string TimeSlot { get; set; }


		/// <summary>
		/// Room_Location.
		/// </summary>
		public string Room_Location { get; set; }


		/// <summary>
		/// Objective1.
		/// </summary>
		public string Objective1 { get; set; }


		/// <summary>
		/// Objective2.
		/// </summary>
		public string Objective2 { get; set; }


		/// <summary>
		/// Objective3.
		/// </summary>
		public string Objective3 { get; set; }


		/// <summary>
		/// Objective4.
		/// </summary>
		public string Objective4 { get; set; }


		/// <summary>
		/// Objective5.
		/// </summary>
		public string Objective5 { get; set; }


		/// <summary>
		/// Speakers.
		/// </summary>
		public IEnumerable<Speaker> Speakers { get; set; }


		/// <summary>
		/// Moderators.
		/// </summary>
		public IEnumerable<Moderator> Moderators { get; set; }


		/// <summary>
		/// Keyword.
		/// </summary>
		public string Keyword { get; set; }


		/// <summary>
		/// Format.
		/// </summary>
		public string Format { get; set; }


		/// <summary>
		/// Translation.
		/// </summary>
		public string Translation { get; set; }


		/// <summary>
		/// Segment.
		/// </summary>
		public string Segment { get; set; }


		/// <summary>
		/// SegmentStatment.
		/// </summary>
		public string SegmentStatment { get; set; }


		/// <summary>
		/// SessionID.
		/// </summary>
		public Guid SessionID { get; set; }


		/// <summary>
		/// SessionFriendlyID.
		/// </summary>
		public string SessionFriendlyID { get; set; }
	}
}