//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;
using CMS.MediaLibrary;

namespace ConvenienceCares
{
	/// <summary>
	/// Represents a page of type <see cref="WebSiteSettings"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class WebSiteSettings : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "ConvenienceCares.WebSiteSettings";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// HeaderLogo.
		/// </summary>
		public IEnumerable<AssetRelatedItem> HeaderLogo { get; set; }


		/// <summary>
		/// Footer_CopyrightText.
		/// </summary>
		public string Footer_CopyrightText { get; set; }


		/// <summary>
		/// Footer_CopyrightUrl.
		/// </summary>
		public string Footer_CopyrightUrl { get; set; }


		/// <summary>
		/// NavigationMenuFolderPath.
		/// </summary>
		public string NavigationMenuFolderPath { get; set; }


		/// <summary>
		/// PageTitleFormat.
		/// </summary>
		public string PageTitleFormat { get; set; }
	}
}