//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace ConvenienceCares.org
{
	/// <summary>
	/// Defines a contract for content types with the <see cref="ISocialMetaTags"/> reusable schema assigned.
	/// </summary>
	public interface ISocialMetaTags
	{
		/// <summary>
		/// Code name of the reusable field schema.
		/// </summary>
		public const string REUSABLE_FIELD_SCHEMA_NAME = "SocialMetaTags";


		/// <summary>
		/// SocialMediaHandler.
		/// </summary>
		public string SocialMediaHandler { get; set; }


		/// <summary>
		/// DefaultTitle.
		/// </summary>
		public string DefaultTitle { get; set; }


		/// <summary>
		/// DefaultDescription.
		/// </summary>
		public string DefaultDescription { get; set; }


		/// <summary>
		/// DefaultImage.
		/// </summary>
		public string DefaultImage { get; set; }
	}
}